### PR TITLE
Added support for the `kotlin.text.Regex` class as built-in

### PR DESCRIPTION
**Pull request by alexmihailov**
Issue #887
 [PR](https://github.com/JetBrains/kotlin/pull/5060) for compiler plugin

### CODE REVIEW

**Comment by sandwwraith** [comment]
I'll repeat here the question by @mcpiroman from compiler PR: "Shouldn't options also be serialized? I don't think they are included in the pattern string."

**Comment by alexmihailov** [comment]
I really forgot about `RegexOption`. In this case, I propose to select two fields for serialization: `pattern` and `options`. Using the composite serializer:
```
{pattern:"^(.+)@(\\S+)$", options:[]}
```
I will propose to make the options field optional:
```
{pattern:"^(.+)@(\\S+)$"}
```
@sandwwraith Leonid, what do you think ?

**Comment by sandwwraith** [comment]
I've studied several different usages of `KSerializer<Regex>` as well as Jackson's approach to this. I've found that while most people serialize regex as string, some indeed need `options`, which may cause problems when parties do not agree on the representation (see, for example, https://github.com/FasterXML/jackson-module-kotlin/issues/210 and https://github.com/FasterXML/jackson-module-kotlin/issues/269 — the former issue is about parsing `{pattern, options}` object while the latter is about parsing `patter` string which was broken by fixing the former.....). The same problem exists for serializing, too: https://github.com/FasterXML/jackson-databind/issues/1959. 

Please tell us what use case for serializing regexes you have and what format works better for it. It may add something to the perspective. However, for now, I think that we shouldn't add any Regex serializer as a standard one — given that there's apparently no standard, universally accepted, and unambiguous representation of it. It's also not a very popular feature.

**Comment by alexmihailov** [comment]
In my case I use Regex without options in Hocon.  I'm using the [config4k](https://github.com/config4k/config4k) library that support Regex from pattern string, but I want to move to kotlinx-serialization and have a built-in serializer for Regex.

**Comment by sandwwraith** [comment]
Given that your usage is Hocon-only, and there's a controversy about representing Regex in Json, I think we won't provide a built-in Regex serializer. It's very easy to provide a custom one where it's needed.

**Pull request closed without merging**
