### PR TITLE
Add value class support to the ProtoBufSchemaGenerator

### PR DESCRIPTION
**Pull request by rotilho**
Closes https://github.com/Kotlin/kotlinx.serialization/issues/2089

### CODE REVIEW

**Review by shanshin — APPROVED** [review]
Thanks for your efforts!

**Comment by shanshin** [comment]
@rotilho, could you please rebase your changes over the `dev` branch?

**Comment by rotilho** [comment]
@shanshin done!

**Comment by shanshin** [comment]
Thanks!

**Review by shanshin — APPROVED** [review]

**Comment by rotilho** [comment]
Super thanks for reviewing it, @shanshin. Just wondering, will this change be in 1.6.3 or are we looking at 1.7.0?

**Pull request merged**
