### PR TITLE
Object serializer support in KType and Type based serializer lookups …

### LINKED ISSUE #656: Getting serializer by object's KClass or KType instance
**What is your use-case and why do you need this feature?**
For object classes, it should be a way to find a serializer. Currently, both `KClass<*>.serializer()` and `serializer<T>()` do not work.

The reason why we need this is that we should somehow serialize objects (that is accepted to be allowed). However, it is not possible if an object is a serialization root.

### PR DESCRIPTION
**Pull request by qwwdfsad**
…on JVM

Fixes #656

### CODE REVIEW

**Comment by sandwwraith** [comment]
I'm not sure limiting this to JVM is a good idea. Are we going to document that? Probably users will be only frustrated by this limitation. Is this for our internal usage? Would it do any good for us since we can use reflection on JVM anyway?

**Comment by qwwdfsad** [comment]
>Is this for our internal usage?

It's both for Ktor (only JVM part _for now_) and external usages.

>Are we going to document that?

We can, but I'd rather keep current documentation to `serializer(KType)` compact and simple. Instead, we should extend support of associated objects for objects on JVM and JS.

> Probably users will be only frustrated by this limitation. Would it do any good for us since we can use reflection on JVM anyway?

Let's not forget that apart from MPP users, we have plenty of JVM-only users as well and it would be really nice if they had a proper experience without reflection (even though it is used under the hood).

**Comment by sandwwraith** [comment]
Then create a separate ticket to support this functionality on Native and JS

**Comment by sandwwraith** [comment]
> Then create a separate ticket to support this functionality on Native and JS

because this PR does not _completely_ fix #656

**Comment by sandwwraith** [comment]
> Then create a separate ticket to support this functionality on Native and JS

because this PR does not _completely_ fix #656

**Pull request merged**
