### PR TITLE
Fix Kotlin user projects build

### PR DESCRIPTION
**Pull request by qurbonzoda**
* Removes @SharedImmutable usages
* Suppresses animal sniffer validation error

### CODE REVIEW

**Comment by sandwwraith** [comment]
1. Can you open PR against `dev` please?
2. Am I right that starting with Kotlin 1.8 `@SharedImmutable` does nothing anyway and can be safely removed?

**Comment by qurbonzoda** [comment]
> * Can you open PR against `dev` please?

Done
> * Am I right that starting with Kotlin 1.8 `@SharedImmutable` does nothing anyway and can be safely removed?

`@SharedImmutable` does nothing in the new K/N memory manager, which is the default one since 1.7.20.
The legacy memory manager is removed completely in 1.9.20, and their is no way to switch back to it.
So the answer is yes. `@SharedImmutable` does nothing and can be safely removed.

**Comment by sandwwraith** [comment]
We plan to do a release with Kotlin 1.9.0. If someone uses old memory manager, it means theirs code will break without this annotation?

**Comment by qurbonzoda** [comment]
> We plan to do a release with Kotlin 1.9.0. If someone uses old memory manager

According to Native team user programs will fail at runtime if the references are used by multiple threads.

**Comment by qwwdfsad** [comment]
> If someone uses old memory manager

We don't have to support it anymore

**Review by sandwwraith — APPROVED** [review]

**Pull request merged**
