### PR TITLE
[Only For Community Branch] 1.9.20-migration: Remove deprecated K/N targets

### PR DESCRIPTION
**Pull request by projedi**
See https://kotl.in/native-targets-tiers for details.

### CODE REVIEW

**Review by woainikk — APPROVED** [review]

**Review by sandwwraith — APPROVED** [review]

**Comment by qwwdfsad** [comment]
It would be nice to target develop for such commits, to reduce the maintenance burden in the future.
YOu can `if` that by Kotlin version from KGP, for example

**Comment by woainikk** [comment]
We discussed it before with @sandwwraith and agreed not to put it into develop now. 
@sandwwraith WDYT?
> It would be nice to target develop for such commits, to reduce the maintenance burden in the future. YOu can `if` that by Kotlin version from KGP, for example

**Comment by sandwwraith** [comment]
@qwwdfsad Given these targets are deprecated only in 1.9.20, we still should be able to develop for them using 1.9.0 in dev.
However, if it is possible to make an `if` on the Kotlin version, it would be more plausible.

**Comment by projedi** [comment]
`if` alone wouldn't be sufficient. Identifiers themselves are now deprecated with an error, so we would have to annotate usages with `@Suppress("DEPRECATION_ERROR")`. Is that more preferable than this PR?

**Comment by qwwdfsad** [comment]
In terms of maintenance, anything targeting `dev` branch is much more preferable than targeting `community-dev` branch. I believe our "Libraries Compilation fix" instruction mentions that

**Comment by projedi** [comment]
Fair enough. Let's try this then: https://github.com/Kotlin/kotlinx.serialization/pull/2325

**Pull request closed without merging**
