### PR TITLE
Respect overriden language version when creating verifyuModule task for

### PR DESCRIPTION
**Pull request by sandwwraith**
JPMS integration.

### CODE REVIEW

**Comment by sandwwraith** [comment]
@woainikk Please cherry-pick to kotlin-community/dev afterwards

**Comment by sandwwraith** [comment]
@qwwdfsad @woainikk

**Review by qwwdfsad — COMMENTED** [review]
If it's `kotlin-merge-blocker`, could you please specify the corresponding YT ticket?

**Comment by sandwwraith** [comment]
@qwwdfsad https://youtrack.jetbrains.com/issue/KT-59171/K2-Prepare-switch-to-LV2.0-in-the-Kotlin-repository

**Review by woainikk — APPROVED** [review]

**Pull request merged**
