### PR TITLE
Support x86_64-based watchOS simulator target

### PR DESCRIPTION
**Pull request by sbogolepov**

### CODE REVIEW

**Comment by sandwwraith** [comment]
Can you please fix the build?

**Comment by fluidsonic** [comment]
Kotlin 1.4.30 is live and this target is missing in 1.1.0-RC. Any news? :)

**Comment by sandwwraith** [comment]
@fluidsonic We need to properly set up our testing infrastructure before releasing the target — as you can see, builds cannot be run now.

**Comment by sbogolepov** [comment]
Superseded by https://github.com/Kotlin/kotlinx.serialization/pull/1366.

**Pull request closed without merging**
