### PR TITLE
Update Dokka to 1.8.20

### PR DESCRIPTION
**Pull request by IgnatBeresnev**
Built the docs locally, nothing looks out of place

### CODE REVIEW

**Comment by sandwwraith** [comment]
@IgnatBeresnev Can you please investigate why `knitCheck` task failed? Maybe Knit can't work with new Dokka version and needs an update

**Comment by IgnatBeresnev** [comment]
Update: I started investigating the problem with knit, but couldn't understand what the problem was exactly - something strange is happening inside knit, so more time is needed to debug it. I've switched to other activities for now, but we'll return to it when we have some time available

**Comment by sandwwraith** [comment]
@IgnatBeresnev I think `knit` was updated in master and dev so you may try again

**Comment by IgnatBeresnev** [comment]
@sandwwraith we tried it in coroutines (https://github.com/Kotlin/kotlinx.coroutines/pull/3776#issuecomment-1679835290), but no luck so far :(

**Comment by whyoleg** [comment]
Closed in favour of https://github.com/Kotlin/kotlinx.serialization/pull/2525

**Pull request closed without merging**
